In [61]:
#import 
import numpy as np 
import pandas as pd 

In [21]:
#import csv's
from numpy import genfromtxt
pictureData = genfromtxt('picture.csv', dtype='str', delimiter=',', skip_header=1)

In [22]:
pic_name = pictureData[:, 1]
pic_latitude = pictureData[:, 2]
pic_latitude = pic_latitude.astype(np.float)
pic_longitude = pictureData[:, 3]
pic_longitude = pic_longitude.astype(np.float)


C:\Users\luvpi\AppData\Local\Temp/ipykernel_23264/1924686583.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  pic_latitude = pic_latitude.astype(np.float)
C:\Users\luvpi\AppData\Local\Temp/ipykernel_23264/1924686583.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  pic_longitude = pic_longitude.astype(np.float)


In [23]:
poleData = genfromtxt('poles.csv', dtype='float', delimiter=',', skip_header=1)
pole_Latitude = poleData[:, 1]
pole_Longitude = poleData[:, 2]

In [53]:
"""testPicture = (pic_latitude[0], pic_longitude[0])
from geopy import distance

d = []
for _,lat,long in poleData:
    #print((lat,long))
    #print(testPicture)
    d.append(distance.distance(testPicture,(lat,long)).km) 

"""
N = 20
sample = np.array(range(N))*50
sample_lat = pic_latitude[sample]
sample_long = pic_longitude[sample]


In [51]:
poleData[1,1:]

array([ 38.73832714, -82.92978037])

In [58]:
dist = np.zeros((poleData.shape[0],N))
# for j in range(latlong.shape[0]):
for j in range(N):
    pic = (pic_latitude[j], pic_longitude[j])
    # for i in range(poleData.shape[0]):
    for i in range(poleData.shape[0]):
        pole = (poleData[i,1], poleData[i,2])
        dist[i,j] = distance.distance(pic,pole).km


In [60]:
"""sortD = d
sortD.sort()
"""
#print(dist[:5, :5])
import pickle
pickle.dump(dist, open('dist.save','wb'))

[[91.57865182 88.36186568 88.55817233 86.35966952 86.34049804]
 [91.55007804 88.33324307 88.52954974 86.33103299 86.31186164]
 [91.50135165 88.2808867  88.47719509 86.27643053 86.25729921]
 [91.51826541 88.30133437 88.49764108 86.29908268 86.27991195]
 [91.49852289 88.2741948  88.47050473 86.2673197  86.24823176]]


In [100]:
df=pd.DataFrame(dist, columns =np.array(range (N)))
df.head()

0          1          2          3          4          5   \
0  91.578652  88.361866  88.558172  86.359670  86.340498  86.326112   
1  91.550078  88.333243  88.529550  86.331033  86.311862  86.297475   
2  91.501352  88.280887  88.477195  86.276431  86.257299  86.242913   
3  91.518265  88.301334  88.497641  86.299083  86.279912  86.265526   
4  91.498523  88.274195  88.470505  86.267320  86.248232  86.233845   

          6          7          8          9          10         11  \
0  86.283916  86.167179  86.087030  86.039204  86.039857  88.375278   
1  86.255279  86.138543  86.058394  86.010567  86.011220  88.346655   
2  86.200724  86.083962  86.003821  85.955987  85.956636  88.294289   
3  86.223330  86.106593  86.026444  85.978617  85.979270  88.314746   
4  86.191665  86.074874  85.994744  85.946900  85.947546  88.287586   

          12         13         14         15         16         17  \
0  86.090945  86.140538  86.160971  86.229155  86.319678  86.414602   
1  86.062308  86.111902  86.132334  86.200519  86.291042  86.385965   
2  86.007735  86.057313  86.077753  86.145935  86.236471  86.331334   
3  86.030359  86.079952  86.100384  86.168569  86.259092  86.354015   
4  85.998656  86.048216  86.068665  86.136846  86.227394  86.322192   

          18         19  
0  91.677584  91.613774  
1  91.649011  91.585200  
2  91.600310  91.536480  
3  91.617199  91.553388  
4  91.597509  91.533658

In [126]:
df['Pole'] = np.arange(poleData.shape[0])
df.head()

0          1          2          3          4          5  \
0  91.578652  88.361866  88.558172  86.359670  86.340498  86.326112   
1  91.550078  88.333243  88.529550  86.331033  86.311862  86.297475   
2  91.501352  88.280887  88.477195  86.276431  86.257299  86.242913   
3  91.518265  88.301334  88.497641  86.299083  86.279912  86.265526   
4  91.498523  88.274195  88.470505  86.267320  86.248232  86.233845   

           6          7          8          9  ...         11         12  \
0  86.283916  86.167179  86.087030  86.039204  ...  88.375278  86.090945   
1  86.255279  86.138543  86.058394  86.010567  ...  88.346655  86.062308   
2  86.200724  86.083962  86.003821  85.955987  ...  88.294289  86.007735   
3  86.223330  86.106593  86.026444  85.978617  ...  88.314746  86.030359   
4  86.191665  86.074874  85.994744  85.946900  ...  88.287586  85.998656   

          13         14         15         16         17         18  \
0  86.140538  86.160971  86.229155  86.319678  86.414602  91.677584   
1  86.111902  86.132334  86.200519  86.291042  86.385965  91.649011   
2  86.057313  86.077753  86.145935  86.236471  86.331334  91.600310   
3  86.079952  86.100384  86.168569  86.259092  86.354015  91.617199   
4  86.048216  86.068665  86.136846  86.227394  86.322192  91.597509   

          19  Pole  
0  91.613774     0  
1  91.585200     1  
2  91.536480     2  
3  91.553388     3  
4  91.533658     4  

[5 rows x 21 columns]

In [150]:
error = pd.DataFrame(columns = ['Pic', 'Difference', 'Nearest', 'Next_Nearest'])
for col in df.columns:
    df2 = df.nsmallest(2,col)
    print(col)
    print(df2.index[0])
    print(df2.index[1])
    vals = df2[col].values
    print(vals)
    error = error.append({'Pic' : col,'Difference':vals[0]-vals[1],'Nearest': df2.index[0], 'Next_Nearest': df2.index[1]}, ignore_index=True)



0
74151
74209
[0.01975628 0.10316289]
1
74393
82523
[0.02743545 0.09198359]
2
74424
74420
[0.0350293 0.0550164]
3
81727
81728
[0.00626419 0.08571192]
4
81727
81726
[0.03467828 0.0598912 ]
5
81727
81726
[0.04502328 0.0467526 ]
6
81726
81725
[0.0149364  0.06374483]
7
81724
81725
[0.03052023 0.06147707]
8
81723
81724
[0.04056799 0.05103578]
9
81723
81722
[0.01263824 0.05810234]
10
81723
81722
[0.01455497 0.05998902]
11
74393
82523
[0.04247222 0.10646562]
12
81723
81724
[0.04456305 0.04717218]
13
81724
81725
[0.01563492 0.08813468]
14
81724
81725
[0.02469317 0.06699415]
15
81725
81726
[0.03283504 0.06717769]
16
81726
81727
[0.04505141 0.04700546]
17
81728
81727
[0.02757683 0.06002586]
18
74151
74209
[0.08915648 0.10742323]
19
74151
74209
[0.0251334  0.09040116]
Pole
0
1
[0 1]


In [170]:
import matplotlib.pyplot as plt

alpha = 25
error_score = error['Difference'].to_numpy()
error_score = 1-np.exp(alpha*error_score)
error_score

array([0.87571342, 0.80085128, 0.39327368, 0.86278321, 0.46758015,
       0.04231177, 0.70483205, 0.5387989 , 0.23025416, 0.67909255,
       0.67885141, 0.79807014, 0.06314626, 0.8367535 , 0.65268552,
       0.57623077, 0.04767722, 0.55568687, 0.36660994, 0.80440206,
       1.        ])

In [171]:
nearest_poles = []
second_nearest = []
picture_loc = []

for i in error.index:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
